apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: com.github.maly7/microservices/chat-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              value: "mongodb://chat-mongodb.default.svc.cluster.local/chat-service"
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongodb-password
                  name: chat-mongodb
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 20
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 20
            periodSeconds: 60
