apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry-deployment
  labels:
    app: service-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: com.github.maly7/microservices/service-registry:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          livenessProbe:
            httpGet:
              port: 8761
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8761
              path: /actuator/health
            initialDelaySeconds: 5
            periodSeconds: 5
