apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: com.github.maly7/microservices/auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATASOURCE_URL
              value: "jdbc:mysql://auth-mysql.default.svc.cluster.local:3306/auth-service"
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: auth-mysql
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 20
            periodSeconds: 60
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            initialDelaySeconds: 20
            periodSeconds: 60
